# -*- coding: utf-8 -*-
"""DataAtRest1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RzTCsrKOTN4Cu9YoI0L-s4l1X3AfZf5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sys

"""# ^^^^^^^^^^^^^^^^^Imports above^^^^^^^^^^^^^^^^^^"""

from google.colab import drive
drive.mount('/content/drive')

"""# Mounted Drive^"""

df = pd.read_csv('/content/drive/MyDrive/PTDataScience/PandasForDataManipulation/sales_predictions.csv')
df

"""# Raw data^^^^^"""

df.fillna("None", inplace=True)

df.head(4)

"""# NaN replaced with "None"
Now the data with NaN is gone and replaced with none for future work
<3

"""

df.rename(columns = {'Item_Identifier': 'ItemID'}, inplace = True)
df.rename(columns = {'Item_Weight': 'ItemWeight'}, inplace = True)
df.rename(columns = {'Item_Fat_Content': 'ItemFatC'}, inplace = True)
df.rename(columns = {'Item_Visibility': 'ItemVis'}, inplace = True)
df.rename(columns = {'Item_Type': 'ItemType'}, inplace = True)
df.rename(columns = {'Item_MRP': 'ItemMRP'}, inplace = True)
df.rename(columns = {'Outlet_Identifier': 'OutletId'}, inplace = True)
df.rename(columns = {'Outlet_Establishment_Year': 'OutletYear'}, inplace = True)
df.rename(columns = {'Outlet_Size': 'OutletSize'}, inplace = True)
df.rename(columns = {'Outlet_Location_Type': 'OutletLocation'}, inplace = True)
df.rename(columns = {'Outlet_Type': 'OutletType'}, inplace = True)
df.rename(columns = {'Item_Outlet_Sales': 'OutletSales'}, inplace = True)

df.head(4)

"""To aviod a mess up, I label each one with the exact name to represent the info given!

Empty for Space()
"""

df.groupby("OutletYear")['OutletSales'].mean().plot(kind='bar');
#This shows the Data by Sales to year or years to sales, but we can get more!

df.groupby(['OutletYear']).sum().plot(kind='pie',y='OutletSales', subplots=True, shadow = True,startangle=90,figsize=(15,10), autopct='%1.1f%%');
#Its not the prettiest but it shows the years and the percentage of sales for each year

df.groupby(['OutletType','OutletLocation']).sum().plot(kind='pie', y='OutletSales', figsize=(15,15), autopct='%1.1f%%');
#This Pie chart shows the type of markets and what percentage of sales they had and includes their tier

df.info

plt.style.use('seaborn')
df['ItemType'].hist(bins = 20,
  edgecolor='black', label='Food Items', color='orange');
plt.xticks(rotation = 60);
plt.title('~ Number of Each Food sold ~', fontsize = 16);
plt.legend();

plt.xticks(rotation = 60);
df['OutletSales'].hist(bins = 10,
  edgecolor='black', label='items sold', color='yellow');
plt.ylabel('Number Of Items', fontsize = 15);
plt.xlabel('Cost Scale', fontsize = 15)
plt.title('~ Number of items sold vs Cost of items ~', fontsize = 16)
plt.legend();